Add Shell Sort 🐙
khoi/sorting-visualization pull request #4
Opened 2019-10-09 03:34 UTC by NghiaTranUIT

## What's it?
This PR introduces ShellSort visualization. 

The implementation is inspired from [Shell Sort - Python - Geeksforgeeks](https://www.geeksforgeeks.org/shellsort/)
 
## Changelogs
- [x] ShellSort logic
- [x] New sort item in the dropdown selection

## Why?
- Visualization is fun 🌮 
- Swag from Hacktoberfest 🧧

2019-10-09 12:38 UTC, khoi requested changes
Awesome, thanks for contributing

2019-10-09 12:38 UTC, khoi commented on algorithms.js
> +  let n = Math.floor(values.length)
`n` doesn't need to be floored ;D

2019-10-09 12:38 UTC, khoi commented on algorithms.js
> +    gap = Math.floor(gap / 2);
Can we use `for` style loop here so it matches the textbook implementation on Wikipedia or GeeksforGeeks

2019-10-09 13:20 UTC, NghiaTranUIT commented
Thank for pointing it out 🌮 Please do a second review 🙌

2019-10-09 13:25 UTC, khoi requested changes

2019-10-09 13:25 UTC, khoi commented on algorithms.js
> +        values[j] = values[j - gap];
Missing `yield` here possibly?

2019-10-09 13:31 UTC, NghiaTranUIT commented on algorithms.js
> +        values[j] = values[j - gap];
opp, I'm noob JS 😮

2019-10-09 13:35 UTC, merged

2019-10-09 13:36 UTC, khoi commented
#2

2019-10-11 09:13 UTC, khoi commented
@all-contributors please add @NghiaTranUIT for his contribution

2019-10-11 09:15 UTC, khoi commented
@all-contributors please add @NghiaTranUIT for his code contribution