Add radix sort (least significant digit)
khoi/sorting-visualization pull request #7
Opened 2019-10-10 08:00 UTC by jdhrnndz

Contributes to #2

2019-10-10 14:46 UTC, khoi commented
@jdhrnndz thank you, I'll review it first thing tmr

2019-10-11 09:02 UTC, khoi requested changes

2019-10-11 09:02 UTC, khoi commented on algorithms.js
> +  let counter = Array.from({ length: 10 }).fill(0, 0);
hmm how does this work? Can it be replaced by: 

```suggestion
  let counter = new Array(10).fill(0);
```

2019-10-11 09:02 UTC, khoi commented on algorithms.js
> +  let values = array.slice(0, array.length);
```suggestion
  let values = [...array];
```

2019-10-11 09:02 UTC, khoi commented on algorithms.js
> +    values = array.slice(0, array.length);
```suggestion
    values = [...array];
```

2019-10-11 09:04 UTC, khoi commented
@jdhrnndz Thank you for your contribution, just some small cosmetic change

2019-10-11 09:05 UTC, khoi requested changes

2019-10-11 09:05 UTC, khoi commented on sketch.js
> +  'radixSort (least significant digit)': radixSortLSD,
```suggestion
  'radixSort (LSD)': radixSortLSD,
```

this will keep the select option width small

2019-10-11 09:18 UTC, khoi commented
@all-contributors please add @jdhrnndz for his code contribution

2019-10-11 09:28 UTC, jdhrnndz commented
Alright, I will adjust the code accdg to these suggestions

2019-10-11 09:35 UTC, khoi approved these changes

2019-10-11 09:36 UTC, khoi commented
@jdhrnndz can u also resolve the conflict, I don't have access to your repo so couldn't change it myself

2019-10-11 09:41 UTC, khoi commented
Seems like your prettier config convert double quote to single, not a big deal. I'll make the change later. TY 🍻

2019-10-11 09:41 UTC, merged

2019-10-11 09:42 UTC, jdhrnndz commented
> Seems like your prettier config converts double quote to single, not a big deal. I'll make the change later. TY 🍻

my bad. i did a hasty conflict resolution  😞